build: Husky config
IsabellePinheiro/what-is-in-your-fridge pull request #1
Opened 2022-12-06 21:01 UTC by IsabellePinheiro

Husky configuration

2022-12-07 09:59 UTC, filip-kis-bm requested changes
Today I learned linting commit messages is a thing 😄 

It's an interesting find but it's not something which is usually enforced via cli. That being said, I see how it can be useful with larger teams/projects. Is this something you are used working with?

I would like to know more about how this works, so I've left a few questions around that.

I've also left some remarks about the PR scope which should always be minimal.

P.S. Don't forget to update the trello board 🎫

2022-12-07 09:59 UTC, filip-kis-bm commented on .husky/commit-msg
> +. "$(dirname -- "$0")/_/husky.sh"
Why is this required?

2022-12-07 09:59 UTC, filip-kis-bm commented on .husky/commit-msg
> +npx commitlint --edit $1
How does this work when we supply 
1. a properly formatted commit message?
2. an invalid commit message?

2022-12-07 09:59 UTC, filip-kis-bm commented on .husky/pre-commit
> +npm test
We haven't setup a testing framework yet so this entire file should either be removed, or we should add a testing framework and at least 1 placeholder test.

I suggest to postpone adding of a testing framework for a subsequent PR as there is a lot going on already.

2022-12-07 09:59 UTC, filip-kis-bm commented on .husky/prepare-commit-msg
> +exec < /dev/tty && git cz --hook || true
What is the purpose of this file?

2022-12-07 09:59 UTC, filip-kis-bm commented on package.json
> +    "test": ""
We should not ship partially implemented stuff if possible. I suggest to remove the `test` script for now as we can add it later in a dedicated PR.

2022-12-07 09:59 UTC, filip-kis-bm commented on package.json
> +    "husky": "^8.0.0"
Can you add a short explanation of how these libs function together (how they interact with each other)?

2022-12-07 09:59 UTC, filip-kis-bm commented on package.json
> +    "pre-commit": "lint-staged",
Does this do anything?

2022-12-07 09:59 UTC, filip-kis-bm commented on pages/index.tsx
> +   <h1>What is in your fridge?</h1>
This change (and other removed files/assets) are not in the scope of this PR `Husky config`. You can leave these changes for now, but in the future try to make PRs in a way that the code changes reflect the PR topic and nothing more.

For instance, by looking at the PR title, I would expect this PR code to contain the husky dependency, it's installation via npm `prepare` lifecycle, and some basic action being done during the git `pre-commit` phase.

2022-12-07 13:59 UTC, IsabellePinheiro commented on .husky/pre-commit
> +npm test
This is an automatic configuration generated by husky, I thought it wouldn't work without this file but I tested and it worked, so I deleted the file :)

2022-12-07 14:07 UTC, IsabellePinheiro commented on .husky/prepare-commit-msg
> +exec < /dev/tty && git cz --hook || true
The `prepare-commit-msg` is a new hook that I created that means that when we run a 'git commit' command, we'll be presented with an interactive Commitizen session to guide us through writing a meaningful commit message.

2022-12-07 14:09 UTC, IsabellePinheiro commented on package.json
> +    "test": ""
The test script was required when I tried to create a commit using the default configuration that Husky prepare for us. Since I removed the hook that was calling the script test, this script could be deleted without cause any problems.

2022-12-07 14:10 UTC, IsabellePinheiro commented on package.json
> +    "pre-commit": "lint-staged",
They were automatically created when I created the project and added husky

2022-12-07 14:57 UTC, IsabellePinheiro commented on package.json
> +    "husky": "^8.0.0"
CommitLint's purpose is to lint our commit messages, we can use the commit-msg hook, which will run every time we try to add a commit message. If the message doesn’t follow the convention, CommitLint will error out, and we’ll have to try again.

Commitizen main purpose is to define a standard way of committing rules and communicating it (using the cli provided by commitizen).

The reasoning behind it is that it is easier to read, and enforces writing descriptive commits.

I'm thinking better right now and feel that both do pretty much the same thing. I guess I'll go only with commit lint

2022-12-07 14:58 UTC, IsabellePinheiro commented on pages/index.tsx
> +   <h1>What is in your fridge?</h1>
Sure, makes sense!

2022-12-07 17:52 UTC, IsabellePinheiro commented on .husky/commit-msg
> +npx commitlint --edit $1
1.
`git commit -m "chore: remove pre-commit file" 

[husky-config 40d1529] chore: remove pre-commit file

 2 files changed, 1 insertion(+), 6 deletions(-)
 delete mode 100755 .husky/pre-commit`


2. 
` git commit -m "Remove test script" 

⧗   input: Remove test script
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky - commit-msg hook exited with code 1 (error)`

2022-12-07 17:56 UTC, IsabellePinheiro commented on .husky/commit-msg
> +. "$(dirname -- "$0")/_/husky.sh"
To be honest, I'm not sure, it was automatically created when I installed husky, but I believe that is to turn the scripts inside husky folder executable

2022-12-08 13:02 UTC, filip-kis-bm commented on .husky/commit-msg
> +. "$(dirname -- "$0")/_/husky.sh"
Alright 👍

2022-12-08 13:03 UTC, filip-kis-bm commented on .husky/commit-msg
> +npx commitlint --edit $1
Nice explanation, thanks!

2022-12-08 13:07 UTC, filip-kis-bm commented on package.json
> +    "pre-commit": "lint-staged",
I'm asking specifically about the line:
```
"pre-commit": "lint-staged",
```

I believe we need to add the `lint-staged` dev dependency and add config for it within `package.json` in order for this script to do anything.

Can you please check if this is the case? 

If my assumption is correct, feel free to either remove this script for now, or setup `lint-staged` dep and accompanying config which will target only staged files with certain extensions and run linter (eg. eslint)/code formatter (eg. prettier) against them during the pre-commit phase.

2022-12-08 13:09 UTC, filip-kis-bm commented on package.json
> +    "husky": "^8.0.0"
Nice explanation. If they are indeed doing the same thing, please choose one and remove the other. On the other hand if they are complimentary, feel free to leave both in.

2022-12-08 13:40 UTC, IsabellePinheiro commented on package.json
> +    "pre-commit": "lint-staged",
done!

2022-12-08 14:18 UTC, filip-kis-bm requested changes

2022-12-08 14:18 UTC, filip-kis-bm commented on package.json
> +    "lint-staged": "^13.1.0"
Judging for the docs, it seems we still need to configure this dependency `lint-staged` so it does a certain action when ran: https://github.com/okonet/lint-staged#installation-and-setup

Lets configure it to concurrently (avoid parallel as this can lead to race conditions) run prettier and then the linter (eslint via `lint` script we already have (not sure if this will work but it's worth a try)).

1. Prettier should check code style and fix it
2. Lint should check code and throw an error (prevent commit) if there are code lint errors.

In order to do this, you may need to install `prettier` as a dev dependency. You will also potentially need to configure prettier and eslint (I believe nextjs comes with eslint so consult nextjs docs on how to configure it if necessary) with regards to rules, files which to ignore, etc.

Prefer having dedicated config files instead of adding the config to `package.json` (eg. for prettier you can use a `.prettierrc` file for rules config, as well as `.prettierignore` for ignoring files/folders such as `node_modules`). `lint-staged` also allows you to target files by extension so let's add a rule to lint/prettify only `ts/tsx` files for now.

You can test prettier part of the `lint-staged` command by adding a couple of blank lines to a random file, and try committing it. Prettier should format the code (remove redundant blank lines) on commit. To test the lint action, you can add an unused reference (eg. `const notUsed = "test"`) and try committing it - linter should prevent commit from finishing successfully and throw a meaningful error.

If you wish, we can handle this in a separate PR or in this one, just let me know.

2022-12-08 14:26 UTC, filip-kis-bm approved these changes
LGTM

2022-12-08 14:29 UTC, merged