styles: Prettier config
IsabellePinheiro/what-is-in-your-fridge pull request #3
Opened 2022-12-12 13:12 UTC by IsabellePinheiro

2022-12-12 17:12 UTC, filip-kis-bm requested changes

2022-12-12 17:12 UTC, filip-kis-bm commented on .vscode/settings.json
> +}
IDE specific stuff (this entire file) usually doesn't belong in an app repo as it is developer specific. It also doesn't belong in this PR since the PR is prettier related and not eslint related.

One pattern with dev specific config is to .gitignore this file (before committing it) and have the config present only locally.

I'm okay with leaving this in since this is a learning project though, so you make the call.

2022-12-12 17:12 UTC, filip-kis-bm commented on pages/index.tsx
> +  return <h1>What is in your fridge?</h1>;
There is one commit "prettier config" but these changes are actually formatting stuff. An improvement here would be to have these changes in a separate commit eg: "chore: run prettier globally" or something similar, since searching for config commits later on could reduce this "noice".

2022-12-12 17:12 UTC, filip-kis-bm commented on .prettierrc.json
> +{}
Please remove the file if it serves no purpose.

2022-12-12 18:25 UTC, IsabellePinheiro commented on pages/index.tsx
> +  return <h1>What is in your fridge?</h1>;
Yep, that makes sense! Noted to next time :)  Can I let the way it is now, though?

2022-12-12 18:27 UTC, IsabellePinheiro commented on .vscode/settings.json
> +}
Gonna add this folder in my .gitignore! You are right :)

2022-12-13 12:36 UTC, filip-kis-bm commented on pages/index.tsx
> +  return <h1>What is in your fridge?</h1>;
Yeah, it's alright since this is a learning project 👍

2022-12-13 12:39 UTC, filip-kis-bm commented on .vscode/settings.json
> +}
Alright 👍 If you add it to .gitignore, just remember to remove this folder first from git as it doesn't make sense having stuff in source control and then ignoring it via .gitignore. This can be handled in a separate PR

2022-12-13 12:41 UTC, filip-kis-bm requested changes

2022-12-13 12:41 UTC, filip-kis-bm commented on pages/index.tsx
> +import React from 'react';
Does it make sense to make quotes consistent across the entire project? I believe it brings value but I'm open to different opinions. We are currently utilising single quotes here but double quotes in some config files.

2022-12-13 13:52 UTC, IsabellePinheiro commented on pages/index.tsx
> +import React from 'react';
It does! I'll check why my quote rule is not changing the config files

2022-12-13 13:53 UTC, IsabellePinheiro commented on .vscode/settings.json
> +}
@filip-kis-bm okay! Gonna do that

2022-12-14 10:27 UTC, filip-kis-bm approved these changes

2022-12-14 13:15 UTC, merged