feat: Create header component
IsabellePinheiro/what-is-in-your-fridge pull request #5
Opened 2022-12-15 13:05 UTC by IsabellePinheiro

Result 

<img width="1315" alt="Screen Shot 2022-12-14 at 11 55 04" src="https://user-images.githubusercontent.com/13142876/207666133-ce40a91a-4520-4f67-a434-e5fb074cbaf1.png">

2022-12-19 09:52 UTC, filip-kis-bm requested changes
Why do we need `dist/output.css`? Can we setup tailwind to work without it?

2022-12-19 09:52 UTC, filip-kis-bm commented on src/components/header/index.tsx
> +      <div className="flex  justify-center items-center">
```suggestion
      <div className="flex justify-center items-center">
```

2022-12-19 09:52 UTC, filip-kis-bm commented on src/components/header/index.tsx
> +      <div className="items-center  flex justify-between hover:underline hover:cursor-pointer">
```suggestion
      <div className="items-center flex justify-between hover:underline hover:cursor-pointer">
```

2022-12-19 09:52 UTC, filip-kis-bm commented on tailwind.config.js
> +        },
Doesn't tailwind come out-of-the box with these colours already? Do these differ from the out-of-the box ones? If yes, we should probably either use a non-standard name for the colour, or make sure that all variants ([100, 200,..]) actually fit within a group (currently this is a mix of custom greys and standard greys right).

My suggestion is to either skip introducing custom colours (and use tailwind ones), or to define the custom colour scheme fully and stick it it (eg. via https://coolors.co/).

2022-12-19 09:52 UTC, filip-kis-bm commented on src/components/header/index.tsx
> +          height={50}
We can make a custom image component which utilises the next/image under-the-hood. This custom image could parse width height tailwind classes provided via `className` prop, and set the correct image width and height internally. This is not a requirement for this PR, but is something that could help us in the long run. Let me know if you have an idea how this could be done.

2022-12-19 17:57 UTC, IsabellePinheiro commented on src/components/header/index.tsx
> +          height={50}
This suggestion will be implemented in a future PR!

2022-12-20 12:48 UTC, filip-kis-bm requested changes
See question: https://github.com/IsabellePinheiro/what-is-in-your-fridge/pull/5#pullrequestreview-1222573354

2022-12-20 13:57 UTC, IsabellePinheiro commented
> dist/output.css

@filip-kis-bm 
Actually, I am following the official documentation (https://tailwindcss.com/docs/installation) step 4 
<img width="1139" alt="Screen Shot 2022-12-20 at 10 55 02" src="https://user-images.githubusercontent.com/13142876/208683358-8432d3bf-6c8d-4984-aafa-424d533f99ea.png">

2022-12-21 10:07 UTC, filip-kis-bm commented
> > dist/output.css
> 
> @filip-kis-bm Actually, I am following the official documentation (https://tailwindcss.com/docs/installation) step 4 <img alt="Screen Shot 2022-12-20 at 10 55 02" width="1139" src="https://user-images.githubusercontent.com/13142876/208683358-8432d3bf-6c8d-4984-aafa-424d533f99ea.png">
> 
> Do you see any reason to avoid this step since is part of the official installation doc?

I believe that installation doc is for bare projects (no framework involved) while we need a framework specific installation guide. There seems to be a nextjs installation guide here: https://tailwindcss.com/docs/guides/nextjs

2022-12-21 14:29 UTC, IsabellePinheiro commented
> > > dist/output.css
> > 
> > 
> > @filip-kis-bm Actually, I am following the official documentation ([tailwindcss.com/docs/installation](https://tailwindcss.com/docs/installation)) step 4 <img alt="Screen Shot 2022-12-20 at 10 55 02" width="1139" src="https://user-images.githubusercontent.com/13142876/208683358-8432d3bf-6c8d-4984-aafa-424d533f99ea.png">
> > Do you see any reason to avoid this step since is part of the official installation doc?
> 
> I believe that installation doc is for bare projects (no framework involved) while we need a framework specific installation guide. There seems to be a nextjs installation guide here: [tailwindcss.com/docs/guides/nextjs](https://tailwindcss.com/docs/guides/nextjs)

You are absolutely right. On my way to fix this.

2022-12-21 17:08 UTC, filip-kis-bm requested changes

2022-12-21 17:08 UTC, filip-kis-bm commented on src/styles/globals.css
> +@tailwind utilities;
Let's rename this file to `tailwind.css`. In the future we can add a new one `global.css` if we need global styles.

2022-12-21 17:08 UTC, filip-kis-bm commented on src/pages/_document.tsx
> +      <body className="bg-gray-100 bg-app bg-no-repeat bg-cover">
What does `bg-app` class do?

2022-12-21 18:40 UTC, IsabellePinheiro commented on src/pages/_document.tsx
> +      <body className="bg-gray-100 bg-app bg-no-repeat bg-cover">
I think I made a typo here, deleted.

2022-12-22 10:04 UTC, filip-kis-bm approved these changes

2022-12-22 12:52 UTC, merged