Create recipe component
IsabellePinheiro/what-is-in-your-fridge pull request #6
Opened 2022-12-16 12:42 UTC by IsabellePinheiro

Result

https://user-images.githubusercontent.com/13142876/208100642-d505bad2-d0f1-4140-8419-1484cbc48aab.mov

2022-12-19 10:04 UTC, filip-kis-bm requested changes

2022-12-19 10:04 UTC, filip-kis-bm commented on package.json
> +    "framer-motion": "^7.10.0",
When picking a new library to work with, we should consider the following:

1. Is it relatively easy to build the functionality ourselves? If yes, we should probably do this.
2. Is the library we found still being maintained and has a significant community around it? If not, we should probably skip the library.
3. Is the library size small enough so it's justified using it? How does tree-shaking influence the final bundle size of our app with regards to this library? How can we benchmark this?

Can we start a discussion here?

2022-12-19 10:04 UTC, filip-kis-bm commented on src/components/recipe/index.tsx
> +      whileTap={{ scale: 0.9 }}
How can we optimise this?

2022-12-19 10:04 UTC, filip-kis-bm commented on src/components/recipe/index.tsx
> +        <h2 className="text-gray-800 text-2xl font-bold leading-tight  mt-4 mb-2">
```suggestion
        <h2 className="text-gray-800 text-2xl font-bold leading-tight mt-4 mb-2">
```

2022-12-19 18:52 UTC, IsabellePinheiro commented on package.json
> +    "framer-motion": "^7.10.0",
@filip-kis-bm I chose this lib because it is constantly updated and widely used to work with animations. As I mentioned before, I'd like to explore more animations in this project and this library seemed to be a very reliable option to use. 

However, I used the [next-bundle-analyzer](https://github.com/josselinbuils/next-bundle-analyzer) - that will chart the bundle so we can see what takes up space - and I discovered that the library uses almost 100kb ( which it's kinda expensive ). 

My opinion is that I should do some vanilla animation for this specific component and use this lib for some more complex situations.


PS: I was never asked to analyze this kind of thing when I decided to use a lib before, so it's pretty new for me, if you believe I should go deeper on this topic please let me know :) And thanks for pushing me to learn something new!

2022-12-20 12:47 UTC, filip-kis-bm commented on package.json
> +    "framer-motion": "^7.10.0",
100kb is relatively a lot.

It makes sense to use largish libs when we are:
1. Not concerned with performance/load times - this is rarely the case with modern web-apps. If we are building an app which is to be used by a lot of users, larger bundle size means longer load times, worse SEO, worse performance. An example of an app where we are not concerned by the bundle size could be an admin panel app (which is used by a couple of people rarely and hence doesn't benefit much from a custom solution)
2. Time limited (using largish libs just for time sake is still to be considered technical debt and should be addressed at some later point when time is not the issue anymore)
3. Considering a lib that provides a functionality that would require 5-10x or more time for a custom implementation (eg. some battle-tested chart library in a chart heavy app)
4. Points 1, 2 are only valid if the lib integration approach is significantly faster than a custom one.

For the purpose of learning, I see more benefit in attempting to recreate lib functionality from scratch as opposed to integrating complete solutions so I propose we try implementing functionality ourselves wherever possible. You can always peek inside certain library source to see how it managed to solve a certain problem. I believe being efficient at this makes you an outstanding dev so it makes sense to me to start thinking this way. WDYT?
 
As for bundle size analysing, can you please check how some libraries (eg. the UI component one and the icon one) influence the final bundle size? Also, `bundlephobia` can be a useful tool when you are considering if a certain library has a reasonable size.

Bonus question: Does [next-bundle-analyzer](https://github.com/josselinbuils/next-bundle-analyzer) take tree-shaking into account?

2022-12-20 12:49 UTC, filip-kis-bm requested changes
See comment: https://github.com/IsabellePinheiro/what-is-in-your-fridge/pull/6#discussion_r1053278226

2022-12-20 13:59 UTC, IsabellePinheiro commented on src/components/recipe/index.tsx
> +      whileTap={{ scale: 0.9 }}
Fixed with vanilla css !

2022-12-21 14:11 UTC, IsabellePinheiro commented on package.json
> +    "framer-motion": "^7.10.0",
I think in this situation where I am now ( working in a demo project ) it makes sense, but in a real one I believe that some libs can help a lot. Of course, we always should consider those premisses involving reliability, frequency of manutenability , popularity and so on, but if the lib has all of there requisites I think it's fine take advantage of something that is already developed and well tested. 

Wow, I checked the bundle size  of my icon libe with bundlephobia and I'm impressed that it uses 227kb this is quite a lot and I'm not even using yet on this project

@filip-kis-bm I couldn't find an oficial answer to your bonus question :/  But I learned an interesting thing that if I add "sideEffects": false in my package.json reduces the bundle size significantly. When we do that, we inform that it can safely prune unused exports.

2022-12-22 09:57 UTC, filip-kis-bm commented on package.json
> +    "framer-motion": "^7.10.0",
I propose to skip using `sideEffects` flag unless we are 100% sure none of our files actually have side-effects (which seems to me that's not the case).

Answer to the bonus question is yes, since tree shaking occurs during the process of generating a bundle, and the analyzer just analyzes the bundle :)

Can we verify our icon and ui component libs support tree shaking? I forgot to mention this in the PR where we added them, but that was the optimal time to check this. Tree shaking is almost a must for any ui or icon library as their size is almost always considerable and we rarely need to use all of their exports. If they do not support tree shaking, we should find alternatives.

2022-12-22 14:00 UTC, IsabellePinheiro commented on package.json
> +    "framer-motion": "^7.10.0",
Thank you for teaching me this! Actually I deleted the icon lib because I'm not using yet

But I checked and tailwindcss is fully tree-shakeable

2022-12-22 14:33 UTC, filip-kis-bm requested changes

2022-12-22 14:33 UTC, filip-kis-bm commented on next.config.js
> +module.exports = withBundleAnalyzer({nextConfig})
Let's revert this change and add a script to package.json which we can run when we are interested in bundle analysis. We don't want this to neither slow down dev builds nor influence prod builds in any way. Something like this might work:
```
    "analyze": "ANALYZE=1 yarn build",
```

2022-12-22 15:01 UTC, IsabellePinheiro commented on next.config.js
> +module.exports = withBundleAnalyzer({nextConfig})
done

2022-12-22 15:40 UTC, filip-kis-bm approved these changes
Nits

2022-12-22 15:40 UTC, filip-kis-bm commented on package.json
> +    "prepublishOnly": "agadoo",
We will probably never publish this as a standalone package so it seems that this script is redundant.

2022-12-22 15:40 UTC, filip-kis-bm commented on next.config.js
> +
Please revert.

2022-12-22 15:53 UTC, merged