Create search bar component
IsabellePinheiro/what-is-in-your-fridge pull request #7
Opened 2022-12-19 14:05 UTC by IsabellePinheiro

Result 

<img width="668" alt="Screen Shot 2022-12-19 at 11 04 17" src="https://user-images.githubusercontent.com/13142876/208443434-84fdc564-c93c-43cd-b9f6-2e58bd38a413.png">

2022-12-20 12:53 UTC, filip-kis-bm requested changes

2022-12-20 12:53 UTC, filip-kis-bm commented on src/components/searchBar/index.tsx
> +}
Seems like prettier didn't run and fix issues on pre-commit stage. Can you fix this please?

2022-12-20 12:53 UTC, filip-kis-bm commented on src/components/searchBar/index.tsx
> +}
```suggestion
interface Props {
  placeholder: string
}
```
or
```suggestion
type Props = {
  placeholder: string
}
```

2022-12-20 12:53 UTC, filip-kis-bm commented on src/components/searchBar/index.tsx
> +  placeholder: string
Why do we need a `placeholder` prop? Are going to have more than one instance of the search bar component?

2022-12-20 12:53 UTC, filip-kis-bm commented on src/components/searchBar/index.tsx
> +        type='text'  value={value} onChange={(event) => { setValue(event.target.value)}}  placeholder={placeholder}/>
Extract onChange callback to a `useCallback`.

2022-12-20 12:53 UTC, filip-kis-bm commented on src/components/searchBar/index.tsx
> +        className='flex w-full mt-4 px-6 py-4 rounded bg-gray-300 border border-gray-600 text-sm text-gray-900'
What does the `border` class do?

2022-12-21 15:32 UTC, IsabellePinheiro commented on src/components/searchBar/index.tsx
> +}
Done!

2022-12-21 15:42 UTC, IsabellePinheiro commented on src/components/searchBar/index.tsx
> +        type='text'  value={value} onChange={(event) => { setValue(event.target.value)}}  placeholder={placeholder}/>
Can I ask why? I think this function is pretty trivial and useCallback is unnecessary here.

2022-12-21 15:55 UTC, IsabellePinheiro commented on src/components/searchBar/index.tsx
> +        className='flex w-full mt-4 px-6 py-4 rounded bg-gray-300 border border-gray-600 text-sm text-gray-900'
it means border-width: 1px; in pure css

2022-12-21 15:57 UTC, IsabellePinheiro commented on src/components/searchBar/index.tsx
> +  placeholder: string
My intention here was to try to create the most generic component I could, so if in the future I decide to add this component in my header, for instance, I could do without need to change the component

2022-12-21 17:28 UTC, filip-kis-bm commented on src/components/searchBar/index.tsx
> +  placeholder: string
Building most-generic first usually leads to wrong abstraction in the long-term. The safest approach is to start non-generic. Later on when you may identify an opportunity to re-use some existing code, and at that point you know what the abstraction should be. Also, building incrementally is less cognitively burdening as opposed to planning ahead too much.

This is a rule of thumb, however, there are sometimes exceptions.

Let's leave this change in for now, but also let's track if this prop will ever be used. If it doesn't get used in the foreseeable future, we will probably forget it, and then the only impact it will have is to take space and attention while reading code.

2022-12-21 17:56 UTC, IsabellePinheiro commented on src/components/searchBar/index.tsx
> +  placeholder: string
hmmm I got your point! Gonna remove the prop then :)

2022-12-21 17:57 UTC, filip-kis-bm commented on src/components/searchBar/index.tsx
> +        type='text'  value={value} onChange={(event) => { setValue(event.target.value)}}  placeholder={placeholder}/>
Questions are always welcome!

There are two points to be made here:
1. Extracted vs inline - JSX is usually the hardest part of a component to read. Extraction of functions alleviate this issue as we minimise js/ts in our jsx/tsx. A general rule of thumb is to keep jsx/tsx as clean as possible.

2. Plain vs memoized (via useCallback) - there is an argument to be made here that memoization worsens performance with simple cases like this. 

On the other hand, having a non-memoized function means it will be remade on every re-render (and the old one will be GC-ed when the runtime chooses to do so). If user long presses a keyboard key and types 50 characters in this input, 50 function references will await the next GC cycle (consider the memory footprint). If we were to pass such a non-memoized function to a memo-ed component, the memo-ed component would re-render even when not necessary (basically on every parent re-render). If we use a non-memoized function in an effect, the effect will run and cleanup on every re-render, instead of when really needed. Issues that arise from these points are usually hard to debug and therefore fix.

If we take all this into account, it makes sense (at least for me) to be consistent with component functions in a sense that:
1. every function is extracted (not in jsx/tsx) if possible
2. every function is wrapped via `useCallback` - the possible performance overhead (for simple use-cases like this one) seems negligible considering we don't have to worry about stuff mentioned in paragraph above.

Does this make sense?

2022-12-21 18:35 UTC, IsabellePinheiro commented on src/components/searchBar/index.tsx
> +        type='text'  value={value} onChange={(event) => { setValue(event.target.value)}}  placeholder={placeholder}/>
Ok, got it! Makes sense to me. If I decide to go with the first approach should I then have to create two files: one with my tsx  code and another with the logic? And then pass the onChange function as a prop?

2022-12-22 09:42 UTC, filip-kis-bm commented on src/components/searchBar/index.tsx
> +        type='text'  value={value} onChange={(event) => { setValue(event.target.value)}}  placeholder={placeholder}/>
By jsx/tsx I meant jsx that the component returns:

```react
const SomeComponent = () => {
const nonMemoizedFunction = () => console.log("nonMemoizedFn");

const memoizedFunction = useCallback(() => console.log("memoizedFn"), []);

 // JSX starts below
return (
<>
  <button onClick={() => console.log("inlineFn")}></button> // 1. worst readability and perf
  <button onClick={nonMemoizedFunction}></button> // 2. better readability but still need to consider caveats described in previous message
  <button onClick={memoizedFunction}></button> // 3. minimal perf impact in simple use-cases, but better readability and don't have to worry about caveats mentioned in previous message
</>
)}
```

It's okay to keep all this in a single file. We can extract later when the need arises.

2022-12-22 16:11 UTC, filip-kis-bm approved these changes

2022-12-22 17:35 UTC, merged