Create button component
IsabellePinheiro/what-is-in-your-fridge pull request #8
Opened 2022-12-19 14:24 UTC by IsabellePinheiro

Result

<img width="135" alt="Screen Shot 2022-12-19 at 11 22 14" src="https://user-images.githubusercontent.com/13142876/208447294-22e3d6da-1e92-40d6-8cef-34466bb8dd30.png">

2022-12-20 12:55 UTC, filip-kis-bm requested changes

2022-12-20 12:55 UTC, filip-kis-bm commented on src/components/button/index.tsx
> +}
```suggestion
interface Props {
  text: string;
}
```

or

```suggestion
type Props = {
  text: string;
}
```

2022-12-20 12:55 UTC, filip-kis-bm commented on src/components/button/index.tsx
> +      {text}
Does it make sense to render `props.children` here?

2022-12-21 15:28 UTC, IsabellePinheiro commented on src/components/button/index.tsx
> +      {text}
I'm not sure if I understood your question, but I changed the code a little bit, let me know if it resolves  :)

2022-12-22 10:00 UTC, filip-kis-bm commented on src/components/button/index.tsx
> +      {text}
If we were to render `{props.children}` instead of `{text}` here, then we could use this custom button component as follows (instead of providing the text prop):
```react
<Button>Lorem ipsum</Button>
```
We can leave this change for later when the need arises.

2022-12-22 10:03 UTC, filip-kis-bm requested changes

2022-12-22 10:03 UTC, filip-kis-bm commented on src/components/button/index.tsx
> +  title: string;
The html button element already accepts a title attribute (used to display a native tooltip).

With the current implementation, we are making it impossible for the tooltip to be displayed. Is this intentional?

2022-12-22 15:09 UTC, IsabellePinheiro commented on src/components/button/index.tsx
> +  title: string;
hmmm, it wasn't. Gonna change the code.

2022-12-22 16:11 UTC, filip-kis-bm approved these changes

2022-12-22 17:41 UTC, merged